spring:
  mvc:
    favicon: false
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity_demo?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qwerty
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-wait: 30000
      query-timeout: 10
      validation-query: SELECT 1
      use-global-data-source-stat: true
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.bradypod.domain.model
  mapper-locations: classpath:com/bradypod/domain/mapper/*.xml

server:
  port: 8080
  use-forward-headers: true

logging:
  level:
    org.springframework: error